### ISSUE TITLE
Suggestion: Use constructors for required parameters and Read Only Properties in Commands and Queries

### ISSUE THREAD

**Issue by awright18** [cbehrends/DotNetCoreCleanArchitectureSample#3]
Properties of Commands and Queries are only ever intended to be read and constructors enforce the required values to be assigned upon creation.  You can add optional constructor parameters for non required parameters, or an overloaded constructor.

Example: https://github.com/cbehrends/DotNetCoreCleanArchitectureSample/blob/ae58f98d6845c841573c8cb17f65ef8493a4ff4b/Claims.Application/Features/Services/Commands/DeleteService.cs#L15-L18

Suggested Version:
```
 public class Command : IRequest 
 { 
     public int Id { get;  } 
    
     public Command(int id)
     {
          Id = id;
     }   
 } 
```
https://github.com/cbehrends/DotNetCoreCleanArchitectureSample/blob/ae58f98d6845c841573c8cb17f65ef8493a4ff4b/Claims.WebApi/Controllers/ServicesController.cs#L88

In this example I could send a Delete command with out an Id

Just by adding a constructor I avoid that problem.

**Comment by cbehrends** [comment]
In this project I will commonly use the Commands as DTO's which requires me to have a setter or the .Net serializer will not set the properties.  Given that I pass the commands in as DTO's I have not needed a constructor in this project (artifact of TDD style, don't build it till ya need it).

https://github.com/cbehrends/DotNetCoreCleanArchitectureSample/blob/bfc5e79f29ecb7e6eaabef9f031825fedd1a2c28/Claims.WebApi/Controllers/ServicesController.cs#L62

I have a habit of keeping the Commands and Queries using the same non-constructor format and using Object Initializers vs Constructors.  The main reason is that Commands which often perform some kind of update to a DB table can wind up having upwards of 10 or more fields.  Once they get this large, I find using constructor logic (just with the Commands typically) starts to become unreadable and I prefer to use Object Initialization simply because it's more human-friendly.  

As far as the required fields thing, I validate the Commands using FluentValidation to ensure that then input is valid.  Constructors with optional fields often require additional work when unit testing such as when using Mocking frameworks which often don't support optional params.
